version: '3.4'

services:
  restapi-service:
    image: restapi-service
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3100:3100
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
