version: '3.4'

services:
  restapi-service:
    image: restapi-service
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3100:3100
